package catalog

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/GoCodeAlone/workflow/capability/inventory"
)

// WriteCatalog renders the portfolio catalog as Markdown to w: a header,
// one block per Project (with a `status:` line so the V1 e2e test can
// assert byte-identity across re-runs), and a `## Tooling Inventory` section
// derived from inventory.BuildCatalog(inv). When inv is nil, the Tooling
// Inventory section is omitted (taxonomy-absent degradation path) and no
// error is returned.
//
// All field values are rendered verbatim — the writer does NOT mutate,
// trim, or normalize Status (V1: byte-identical preservation). Markdown-
// special characters in table cells (category, release) are escaped via
// escapeTableCell; Status is rendered as free-form lines (not a cell) so
// multi-line human curation survives intact.
func WriteCatalog(w io.Writer, projects []Project, inv *inventory.Inventory) error {
	var b strings.Builder

	b.WriteString("# Portfolio Catalog\n\n")
	b.WriteString("<!-- Generated by `wfctl portfolio scan`. Machine-derived fields are\n")
	b.WriteString("     rewritten each scan; the `status:` line is HUMAN-CURATED and\n")
	b.WriteString("     preserved byte-identical across re-scans (do not edit machine fields\n")
	b.WriteString("     here — edit the source repo; do edit the status: line). -->\n\n")

	// Per-project blocks. Sort for deterministic output (repo-lexical).
	sorted := append([]Project(nil), projects...)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Repo < sorted[j].Repo
	})
	for _, p := range sorted {
		writeProjectBlock(&b, p)
	}

	// Tooling Inventory section (C4): derived from capability/inventory.
	// Omitted entirely when inv is nil (degradation path).
	if inv != nil {
		writeToolingInventory(&b, inv)
	}

	_, err := io.WriteString(w, b.String())
	return err
}

// writeProjectBlock renders one project entry. The `status:` line is
// rendered VERBATIM from p.Status (V1) — multi-line status is preserved as
// indented continuation lines.
func writeProjectBlock(b *strings.Builder, p Project) {
	fmt.Fprintf(b, "## %s\n\n", p.Repo)
	fmt.Fprintf(b, "- category: %s\n", escapeTableCell(p.Category))
	fmt.Fprintf(b, "- visibility: %s\n", escapeTableCell(p.Visibility))
	if p.Scan.LastCommitISO != "" {
		fmt.Fprintf(b, "- last-commit: %s\n", escapeTableCell(p.Scan.LastCommitISO))
	}
	if p.Scan.Uncommitted {
		b.WriteString("- uncommitted-changes: true\n")
	}
	if p.Scan.Remote != "" {
		fmt.Fprintf(b, "- remote: %s\n", escapeTableCell(p.Scan.Remote))
	}
	if p.Release.LatestRelease != "" {
		fmt.Fprintf(b, "- latest-release: %s\n", escapeTableCell(p.Release.LatestRelease))
	}
	prsField := fmt.Sprintf("%d", p.Release.OpenPRs)
	if p.Release.ReleaseGHAbsent {
		prsField = "?"
	}
	issuesField := fmt.Sprintf("%d", p.Release.OpenIssues)
	if p.Release.ReleaseGHAbsent {
		issuesField = "?"
	}
	fmt.Fprintf(b, "- open-prs: %s\n", prsField)
	fmt.Fprintf(b, "- open-issues: %s\n", issuesField)
	if p.Provides != "" {
		fmt.Fprintf(b, "- provides: %s\n", escapeTableCell(p.Provides))
	}
	if p.FollowUpCount > 0 {
		fmt.Fprintf(b, "- open-followups: %d\n", p.FollowUpCount)
	}

	// status: line — VERBATIM, may be multi-line (indented continuation).
	b.WriteString("\nstatus:\n")
	if p.Status != "" {
		for _, line := range strings.Split(p.Status, "\n") {
			fmt.Fprintf(b, "  %s\n", line)
		}
	}
	b.WriteString("\n")
}

// writeToolingInventory renders the C4 tooling inventory section from
// inventory.BuildCatalog(inv). Lists each capability with its providers.
func writeToolingInventory(b *strings.Builder, inv *inventory.Inventory) {
	cat := inventory.BuildCatalog(inv)
	b.WriteString("## Tooling Inventory\n\n")
	b.WriteString("<!-- Derived from capability/inventory (taxonomy-mapped capabilities).\n")
	b.WriteString("     Regenerated each scan from the registry + local plugin manifests. -->\n\n")
	if len(cat.Capabilities) == 0 {
		b.WriteString("_No taxonomy-mapped capabilities found._\n\n")
		return
	}
	currentCategory := ""
	for _, cap := range cat.Capabilities {
		if cap.Category != currentCategory {
			if currentCategory != "" {
				b.WriteString("\n")
			}
			fmt.Fprintf(b, "### %s\n\n", titleCase(cap.Category))
			currentCategory = cap.Category
		}
		fmt.Fprintf(b, "- **%s** (`%s`)", cap.Name, cap.ID)
		if cap.Lifecycle != "" {
			fmt.Fprintf(b, " _%s_", cap.Lifecycle)
		}
		if len(cap.Providers) > 0 {
			names := make([]string, 0, len(cap.Providers))
			for _, pr := range cap.Providers {
				names = append(names, pr.Name)
			}
			fmt.Fprintf(b, " — %s", strings.Join(names, ", "))
		}
		b.WriteString("\n")
	}
	b.WriteString("\n")
}

// escapeTableCell neutralizes markdown table-breaking characters (|, newline)
// in a value rendered into a table cell or inline list item. Pipe becomes
// the escaped sequence; newlines become spaces.
func escapeTableCell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}

// titleCase returns s with its first rune upper-cased (for section headers).
func titleCase(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = []rune(strings.ToUpper(string(r[0])))[0]
	return string(r)
}
